### ISSUE TITLE
Update Status

### ISSUE THREAD

**Issue by gamingneeds** [ExcuseMi/rocketleaguelivestats#2]
Any way I could convince you to update this project?

**Comment by ExcuseMi** [comment]
Hi, haven't looked at this project for a while.
Provided that the player identifiers can still be found in the logs and we could get an API key for http://documentation.rocketleaguestats.com/#introduction, this might still work. (Requested one).

We will see.

**Comment by gamingneeds** [comment]
Hey, I'll cross my fingers. I contacted a friend of mine about getting you API access that is more up-to-date than RLS. Is there a way I can send you the API access privately tomorrow?

Thanks :)

**Comment by ExcuseMi** [comment]
Can you find an email in my bio.

**Comment by gamingneeds** [comment]
Yeah, got it. Thanks.

I'll shoot you an email soon. :)

**Comment by gamingneeds** [comment]
Seems your contact info disappeared but sent you a verification email to what I _think_ your email was. :)

**Comment by ExcuseMi** [comment]
check again, didn't receive anything.

**Comment by gamingneeds** [comment]
I sent to the right email, maybe check other folders? I verified the email I sent to was the one listed on your profile.

Sent a second message.
